In [10]:
import numpy as np
a = np.arange(1, 7).reshape(2, 3)
print(a, a+a, a-a, a*a, sep = '\n')
# dot product - dot product와 계산하기 위해서는 앞행렬의 열의 개수와 뒷행렬의 행의 개수가 같아야 가능
np.dot(a, a.T) # == a.dot(a.T)
a.dot(a.T)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]


array([[14, 32],
       [32, 77]])