In [18]:
# Numerical Python(Numpy) - Part 1
# de facto standard(사실상의 표준)
import numpy as np
a = [1, 2, 3]
print(a * 3)
list(map(lambda x : 3 * x, a))
b = np.array([1,2,3])
print(b * 3)

# Numpy Dimension
a = np.array([1,4,5,8], float) # Numpy는 행렬안에 정수, 실수만 저장가능(문자열 저장 불가 - list와의 차이점)
type(a)
a.dtype, a.shape
# Array shape
# Vector(1차원)
vec = np.array([1, 4, 5, 8])
vec
vec.shape, type(vec.shape)
# Matrix(2차원)
matrix = np.array([[1,2,3], [4,5,16]])
print(matrix.shape)
# Tensor(3차원 이상)
tensor = np.arange(1,25).reshape(2,3,4)
tensor
# element 개수
vec.size, matrix.size, tensor.size
a = np.array([1,2,3], dtype = np.float32)
a
b = np.array([1,2,3], np.int16)
b
# reshape(행의개수, 열의개수)
matrix.shape
print(matrix.reshape(6,))
print(matrix.reshape(3,-1))
print(matrix.reshape(3,-1).shape) # -1은 numpy가 알아서 맞춰줌(단, size가 동일)
print(tensor.reshape(3,-1).shape)

# flatten : 다차원을 1차원으로 변경해주는 함수
tensor.reshape(-1,)
tensor.flatten()

# Indexing & Sclicing
matrix

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]
(2, 3)
[ 1  2  3  4  5 16]
[[ 1  2]
 [ 3  4]
 [ 5 16]]
(3, 2)
(3, 8)


array([[ 1,  2,  3],
       [ 4,  5, 16]])