In [52]:
# 단위행렬 - identity
import numpy as np
import matplotlib.pyplot as plt

np.identity(n=3, dtype=np.int16)
np.identity(3)

# eye 대각선이 1인 행렬
np.eye(N=3, M=5, k=2, dtype=np.int32) # k : start index
np.eye(4, 3, -1)

# diag - 대각선 위치의 값을 추출
np.diag(np.arange(9).reshape(3,3))
np.diag(np.arange(9).reshape(3,3), k=1) # k : start index
np.eye(3)

# Random sampling
np.random.seed(seed=2021)
np.random.random()
# 균등분포
np.random.uniform(size=10)
# 정규분포
np.random.normal(size=10)
# 정규분포 - N(1,2)
np.random.normal(1, 2, size = 10)
'''
# 표준 정규분포 - N(0,1)
np.random.randn(10)
rand_norm = np.random.randn(1000)
plt.hist(rand_norm)
plt.show()
'''

# Operation
# Sum과 Axis
a = np.arange(1, 13).reshape(3,4)
a.sum()

# column의 합, row 방향 
a.sum(axis=0)
# row의 합, column 방향
a.sum(axis=1)
b = np.arange(1,25).reshape(2,3,4)
print(b)
print(b.sum(axis=0)) # (2, 3, 4) - > (3, 4)
print(b.sum(axis=1)) # (2, 3, 4) - > (2, 4)
print(b.sum(axis=2)) # (2, 3, 4) - > (2, 3)

# 통계, 수학 함수
print(b.mean(), a.var(), a.std())
print(a.mean(), a.mean(axis=0), a.mean(axis=1))
np.exp(a)

# Concatenate
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,7).reshape(1,2)
np.vstack((a,b))
np.concatenate((a,b), axis = 0)
# 전치행렬(Transpose) : (1,2) -> (2,1)
b.T
np.hstack((a,b.T))
np.concatenate((a,b.T), axis = 1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[15 18 21 24]
 [51 54 57 60]]
[[10 26 42]
 [58 74 90]]
12.5 11.916666666666666 3.452052529534663
6.5 [5. 6. 7. 8.] [ 2.5  6.5 10.5]


array([[1, 2, 5],
       [3, 4, 6]])