In [142]:
import numpy as np
import matplotlib.pyplot as plt

a = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(a)

m = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
print(m[1][2], m[2][4], m[1][1:3], m[1:3, 2], m[0:2, 3:5])

n = m.reshape(15,)
x, y, z = list(), list(), list()
for i in range(len(n)):
    if n[i] % 3 == 0 :
        x.append(n[i])
    elif n[i] % 4 == 1:
        y.append(n[i])
    elif n[i] % 3 == 0 and n[i] % 4 == 1:
        z.append(n[i])
print(x, y, z, sep = '\n')
print(3*np.eye(5, 5, -1) + 2*np.eye(5, 5) + np.eye(5, 5, 1))

x = np.random.uniform(1, 10, size = (5,6))
print(x.reshape(30,))
print(x.reshape(30,)[[np.argmax(x.reshape(30,))]], x.sum(axis=1)) # 전체의 최댓값, 각 행의 합
for i, k, u in zip(list(range(5)), np.argmax(x, axis = 1), np.argmin(x, axis = 0)):
    print(x[i][k], x.T[i][u]) # 행의 최댓값, 열의 최솟값
print(x.mean(axis=0)) # 열의 평균


[[10 20 30 40]
 [50 60 70 80]]
7 14 [6 7] [ 7 12] [[3 4]
 [8 9]]
[0, 3, 6, 9, 12]
[1, 5, 13]
[]
[[2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [0. 3. 2. 1. 0.]
 [0. 0. 3. 2. 1.]
 [0. 0. 0. 3. 2.]]
[4.15397964 2.4392316  9.95019533 3.25378632 6.83785627 8.93517854
 5.48628695 6.76835191 9.11334548 1.18355089 2.7159777  2.28125303
 3.98430928 6.8740211  4.22112375 5.69698855 4.49140412 7.94161778
 9.07002515 8.75041177 8.51043923 7.51866528 8.92458825 4.73857582
 8.02011615 1.81791345 4.22688396 1.56472199 4.28360527 3.8383867 ]
[9.95019533] [35.57022769 27.54876596 33.20946458 47.5127055  23.75162753]
9.950195327499333 3.9843092751987053
9.11334548329527 1.8179134529659287
7.9416177825202166 4.221123751450239
9.070025149192578 1.1835508858440975
8.020116153299009 2.7159776995725013
[6.14294343 5.32998597 7.20439755 3.8435426  5.45068632 5.54700237]
